name: CI
on: [push]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy Environment Laravel Configuration
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Create SQLite Database and Migrate
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate
    - name: Execute PHPUnit Tests
      run: vendor/bin/phpunit
